<?php
/**
 * Created by PhpStorm.
 * User: lapiscine
 * Date: 03/12/2018
 * Time: 22:26
 */

namespace AppBundle\Repository;


/**
 * Class EmployesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployesRepository extends \Doctrine\ORM\EntityRepository
{

}